# Analyze scores for each role

In [3]:
import json
import os
import torch
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.subplots as sp
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from pathlib import Path
from tqdm import tqdm


In [7]:
# or roles_240
dir = "roles" 

# or 240
n_questions = 30
n_prompt_types = 2


## Score statistics

In [ ]:
# load data from data/extract_scores
score_dir = f"/workspace/{dir}/extract_scores"

# iterate through each json file in the directory
scores = {}
for file in os.listdir(score_dir):
    if file.endswith(".json"):
        with open(os.path.join(score_dir, file), "r") as f:
            scores[file.replace(".json", "")] = json.load(f)

print(f"Found {len(scores.keys())} roles with scores")


Found 275 traits with scores


In [5]:
# Analyze refusals and clean data
refusal_info = {}
scores_clean = {}

for role, score_obj in scores.items():
    refusals = []
    cleaned_scores = {}
    
    # Check each score for refusals
    for key, value in score_obj.items():
        if value == "REFUSAL":
            refusals.append(key)
            cleaned_scores[key] = 0  # Replace refusals with NaN
        else:
            cleaned_scores[key] = float(value)  # Ensure numeric
    
    scores_clean[role] = cleaned_scores
    refusal_info[role] = {
        "refusals": refusals,
        "refusal_count": len(refusals)
    }

# Show refusal statistics
total_refusals = sum(info["refusal_count"] for info in refusal_info.values())
roles_with_refusals = sum(1 for info in refusal_info.values() if info["refusal_count"] > 0)

print(f"Refusal Statistics:")
print(f"Total refusals across all roles: {total_refusals}")
print(f"Roles with refusals: {roles_with_refusals}")

if total_refusals > 0:
    sorted_refusals = sorted(refusal_info.items(), key=lambda x: x[1]["refusal_count"], reverse=True)
    print(f"\nTop 10 roles with most refusals:")
    for role, info in sorted_refusals[:10]:
        if info["refusal_count"] > 0:
            print(f"  {role}: {info['refusal_count']} refusals - {info['refusals']}")

Refusal Statistics:
Total refusals across all roles: 9
Roles with refusals: 4

Top 10 roles with most refusals:
  rogue: 3 refusals - ['default_p1_q28', 'default_p2_q28', 'default_p3_q24']
  smuggler: 3 refusals - ['default_p1_q25', 'default_p4_q2', 'default_p4_q26']
  spy: 2 refusals - ['default_p1_q28', 'default_p4_q15']
  caveman: 1 refusals - ['default_p2_q20']


In [9]:
# Create numpy arrays using cleaned scores (refusals as NaN)

scores_np = {}

for role, cleaned_scores in scores_clean.items():
    # Create 3D array: [type, prompt, question]
    scores_3d = np.full((n_prompt_types, 5, n_questions), np.nan)
    
    # Extract scores for each type, prompt, and question
    for prompt_idx in range(5):
        for question_idx in range(n_questions):
            # pos scores
            pos_key = f"pos_p{prompt_idx}_q{question_idx}"
            if pos_key in cleaned_scores:
                scores_3d[0, prompt_idx, question_idx] = cleaned_scores[pos_key]
            
            # default scores
            default_key = f"default_p{prompt_idx}_q{question_idx}"
            if default_key in cleaned_scores:
                scores_3d[1, prompt_idx, question_idx] = cleaned_scores[default_key]
    
    scores_np[role] = scores_3d

print(f"Created numpy arrays for {len(scores_np)} roles")
print(f"Shape of each array: {next(iter(scores_np.values())).shape}")
print(f"Example (first role): {list(scores_np.keys())[1]}")
example_role = list(scores_np.keys())[1]
print(f"Pos scores for first 2 prompts, 5 questions:\n{scores_np[example_role][0, :2, :5]}")
print(f"Default scores for first 2 prompts, 5 questions:\n{scores_np[example_role][1, :2, :5]}")

Created numpy arrays for 275 roles
Shape of each array: (2, 5, 30)
Example (first role): collaborator
Pos scores for first 2 prompts, 5 questions:
[[100. 100. 100. 100. 100.]
 [100. 100. 100.  90. 100.]]
Default scores for first 2 prompts, 5 questions:
[[90. 95. 50. 90. 90.]
 [80. 90. 70. 80. 80.]]


In [ ]:
# Calculate simplified statistics for each role
stats = {}

for role, scores_3d in scores_np.items():
    pos_scores = scores_3d[0]  # shape: (5, 20) 
    neg_scores = scores_3d[1]  # shape: (5, 20)
    
    # Mean difference between pos and neg across all samples
    pos_minus_neg_mean = np.nanmean(pos_scores - neg_scores)
    
    # Count all pos/neg pairs with same prompt_index and question_index
    high_pos_low_neg_count = 0
    large_diff_count = 0
    
    # Check all 100 pairs (5 prompts × 20 questions)
    for prompt_idx in range(5):
        for question_idx in range(20):
            pos_val = pos_scores[prompt_idx, question_idx]
            neg_val = neg_scores[prompt_idx, question_idx]
            
            # Skip if either value is NaN
            if not (np.isnan(pos_val) or np.isnan(neg_val)):
                # Count high pos, low neg cases
                if pos_val > 50 and neg_val < 50:
                    high_pos_low_neg_count += 1
                
                # Count large difference cases  
                if abs(pos_val - neg_val) > 40:
                    large_diff_count += 1
    
    stats[role] = {
        "pos_minus_neg_mean": pos_minus_neg_mean,
        "high_pos_low_neg_count": high_pos_low_neg_count,
        "large_diff_count": large_diff_count
    }

# Show example statistics for first role
example_role = list(stats.keys())[0]
print(f"Example statistics for '{example_role}':")
for key, value in stats[example_role].items():
    if isinstance(value, float):
        print(f"  {key}: {value:.2f}")
    else:
        print(f"  {key}: {value}")

print(f"\nCalculated statistics for {len(stats)} roles")

# Show summary of counts
high_pos_counts = [s["high_pos_low_neg_count"] for s in stats.values()]
large_diff_counts = [s["large_diff_count"] for s in stats.values()]
print(f"\nHigh pos, low neg count distribution: min={min(high_pos_counts)}, max={max(high_pos_counts)}, mean={np.mean(high_pos_counts):.1f}")
print(f"Large diff count distribution: min={min(large_diff_counts)}, max={max(large_diff_counts)}, mean={np.mean(large_diff_counts):.1f}")

# Export to CSV
stats_df = pd.DataFrame.from_dict(stats, orient='index')
stats_df.index.name = 'role'
stats_df.to_csv('./results/pos_neg.csv')
print(f"\nExported statistics to pos_neg.csv")
print(f"Shape: {stats_df.shape}")

Example statistics for 'absolutist':
  pos_minus_neg_mean: 21.75
  high_pos_low_neg_count: 25
  large_diff_count: 25

Calculated statistics for 240 traits

High pos, low neg count distribution: min=0, max=100, mean=79.6
Large diff count distribution: min=0, max=100, mean=79.4

Exported statistics to pos_neg.csv
Shape: (240, 3)


In [ ]:
# Calculate pos - default statistics similar to pos - neg
pos_default_stats = {}

for role, scores_3d in scores_np.items():
    pos_scores = scores_3d[0]      # shape: (5, 20) 
    default_scores = scores_3d[2]  # shape: (5, 20)
    
    # Mean difference between pos and default across all samples
    pos_minus_default_mean = np.nanmean(pos_scores - default_scores)
    
    # Count all pos/default pairs with same prompt_index and question_index
    high_pos_low_default_count = 0
    large_diff_count = 0
    
    # Check all 100 pairs (5 prompts × 20 questions)
    for prompt_idx in range(5):
        for question_idx in range(20):
            pos_val = pos_scores[prompt_idx, question_idx]
            default_val = default_scores[prompt_idx, question_idx]
            
            # Skip if either value is NaN
            if not (np.isnan(pos_val) or np.isnan(default_val)):
                # Count high pos, low default cases
                if pos_val > 50 and default_val < 50:
                    high_pos_low_default_count += 1
                
                # Count large difference cases  
                if abs(pos_val - default_val) > 40:
                    large_diff_count += 1
    
    pos_default_stats[role] = {
        "pos_minus_default_mean": pos_minus_default_mean,
        "high_pos_low_default_count": high_pos_low_default_count,
        "large_diff_count": large_diff_count
    }

# Show example statistics for first role
example_role = list(pos_default_stats.keys())[0]
print(f"Example pos-default statistics for '{example_role}':")
for key, value in pos_default_stats[example_role].items():
    if isinstance(value, float):
        print(f"  {key}: {value:.2f}")
    else:
        print(f"  {key}: {value}")

print(f"\nCalculated pos-default statistics for {len(pos_default_stats)} roles")

# Show summary of counts
high_pos_counts = [s["high_pos_low_default_count"] for s in pos_default_stats.values()]
large_diff_counts = [s["large_diff_count"] for s in pos_default_stats.values()]
print(f"\nHigh pos, low default count distribution: min={min(high_pos_counts)}, max={max(high_pos_counts)}, mean={np.mean(high_pos_counts):.1f}")
print(f"Large diff count distribution: min={min(large_diff_counts)}, max={max(large_diff_counts)}, mean={np.mean(large_diff_counts):.1f}")

# Export to CSV
pos_default_df = pd.DataFrame.from_dict(pos_default_stats, orient='index')
pos_default_df.index.name = 'role'
pos_default_df.to_csv('./results/pos_default.csv')
print(f"\nExported pos-default statistics to pos_default.csv")
print(f"Shape: {pos_default_df.shape}")

Example pos-default statistics for 'absolutist':
  pos_minus_default_mean: 22.75
  high_pos_low_default_count: 25
  large_diff_count: 25

Calculated pos-default statistics for 240 traits

High pos, low default count distribution: min=0, max=100, mean=47.1
Large diff count distribution: min=0, max=100, mean=46.8

Exported pos-default statistics to pos_default.csv
Shape: (240, 3)
